version: 1
formatters:
  brief: {format: "%(levelname)s %(message)s"}
  long:  {format: "%(asctime)s %(levelname)s %(name)s: %(message)s"}
handlers:
  console:
    class: logging.StreamHandler
    formatter: brief
    level: INFO
loggers:
  mcp:
    level: INFO
    handlers: [console]
    propagate: false
root:
  level: INFO
  handlers: [console]
