name: API Release & Deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version (e.g. v0.1.0)"
        required: true
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read
  packages: write

jobs:
  build-and-push-ghcr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/mcp-api
          tags: |
            type=raw,value=${{ github.event.inputs.version || github.ref_name }}
            type=ref,event=tag

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        if: ${{ secrets.GHCR_TOKEN != '' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build & (conditional) Push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: ${{ secrets.GHCR_TOKEN != '' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy-render:
    needs: build-and-push-ghcr
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy (webhook)
        env:
          RENDER_HOOK: ${{ secrets.RENDER_API_DEPLOY_HOOK }}
        run: |
          if [ -z "${RENDER_HOOK}" ]; then
            echo "❌ Missing RENDER_API_DEPLOY_HOOK secret"; exit 1
          fi
          echo "Calling Render webhook..."
          curl -fsSL -X POST "${RENDER_HOOK}"
          echo "✅ Render deploy triggered"
